<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:decision="http://www.bonitasoft.org/ns/bpm/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/bpm/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/bpm/process">
  <process:MainProcess xmi:id="_r9-4oKflEfGZSb5q5b0p5g" name="MyDiagram" bonitaModelVersion="9">
    <elements xmi:type="process:Pool" xmi:id="_r9_fsKflEfGZSb5q5b0p5g" name="RescueSync">
      <elements xmi:type="process:Lane" xmi:id="_7XVHkKftEfGZSb5q5b0p5g" name="Sistema Nacional">
        <elements xmi:type="process:ServiceTask" xmi:id="__CbgUKftEfGZSb5q5b0p5g" name="Validacion de ofertas" outgoing="_LBHisKyKEfGxAq-kOcKFjQ" incoming="_AZL34KfuEfGZSb5q5b0p5g _rsFlowTimerToValid">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="__Cd8kaftEfGZSb5q5b0p5g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="__Cd8kKftEfGZSb5q5b0p5g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="__Cd8kqftEfGZSb5q5b0p5g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="__Cd8k6ftEfGZSb5q5b0p5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="__Cd8lKftEfGZSb5q5b0p5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="__Cd8laftEfGZSb5q5b0p5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="__Cd8l6ftEfGZSb5q5b0p5g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="__Cd8lqftEfGZSb5q5b0p5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="__h1KAKyLEfGxAq-kOcKFjQ" name="Clasificacion de ofertas" outgoing="__2C78KyKEfGxAq-kOcKFjQ" incoming="_LBHisKyKEfGxAq-kOcKFjQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_KTm8cqyKEfGxAq-kOcKFjQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_KTm8cayKEfGxAq-kOcKFjQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_KTm8c6yKEfGxAq-kOcKFjQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_KTm8dKyKEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_KTnjgKyKEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_KTnjgayKEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_KTnjg6yKEfGxAq-kOcKFjQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_KTnjgqyKEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_zfop0KyTEfGxAq-kOcKFjQ" name="Registrar compromiso de recursos" outgoing="_6VJwIKyTEfGxAq-kOcKFjQ" incoming="_HSuEsKySEfGxAq-kOcKFjQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_F0ZskaySEfGxAq-kOcKFjQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_F0ZskKySEfGxAq-kOcKFjQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_F0ZskqySEfGxAq-kOcKFjQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_F0Zsk6ySEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_F0ZslKySEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_F0ZslaySEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_F0Zsl6ySEfGxAq-kOcKFjQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_F0ZslqySEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_C1-aUKyXEfGxAq-kOcKFjQ" name="Registrar finalizacion" outgoing="_HybtQKyXEfGxAq-kOcKFjQ" incoming="_otVdgKyWEfGxAq-kOcKFjQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ncUhkayWEfGxAq-kOcKFjQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ncUhkKyWEfGxAq-kOcKFjQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ncUhkqyWEfGxAq-kOcKFjQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_ncUhk6yWEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_ncUhlKyWEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_ncUhlayWEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_ncUhl6yWEfGxAq-kOcKFjQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_ncUhlqyWEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_GjEXIKyXEfGxAq-kOcKFjQ" name="Liberar recursos" outgoing="_byGgsKyXEfGxAq-kOcKFjQ" incoming="_HybtQKyXEfGxAq-kOcKFjQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_GjEXIqyXEfGxAq-kOcKFjQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_GjEXIayXEfGxAq-kOcKFjQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_GjEXI6yXEfGxAq-kOcKFjQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_GjEXJKyXEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_GjEXJayXEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_GjEXJqyXEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_GjEXKKyXEfGxAq-kOcKFjQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_GjEXJ6yXEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_r9_fsaflEfGZSb5q5b0p5g" name="Municipio" actor="_XDEoIKfpEfGZSb5q5b0p5g">
        <elements xmi:type="process:StartEvent" xmi:id="_r9_fsqflEfGZSb5q5b0p5g" name="Ocurre emergencia" outgoing="_r-AG1KflEfGZSb5q5b0p5g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_r-AGwKflEfGZSb5q5b0p5g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_r-AGwaflEfGZSb5q5b0p5g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_r-AGwqflEfGZSb5q5b0p5g" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_r-AGw6flEfGZSb5q5b0p5g" name="Registrar emergencia" outgoing="_-b1XMKfpEfGZSb5q5b0p5g" incoming="_r-AG1KflEfGZSb5q5b0p5g" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_r-AGxKflEfGZSb5q5b0p5g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_r-AGxaflEfGZSb5q5b0p5g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_r-AGxqflEfGZSb5q5b0p5g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_r-AGx6flEfGZSb5q5b0p5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_r-AGyKflEfGZSb5q5b0p5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_r-AGyaflEfGZSb5q5b0p5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_r-AGyqflEfGZSb5q5b0p5g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_r-AGy6flEfGZSb5q5b0p5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_r-AGzKflEfGZSb5q5b0p5g">
            <targetForm xmi:type="expression:Expression" xmi:id="_r-AGzaflEfGZSb5q5b0p5g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_r-AGzqflEfGZSb5q5b0p5g"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_r-AGz6flEfGZSb5q5b0p5g" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_ABYz0KyMEfGxAq-kOcKFjQ" name="Visualizar ofertas validas" outgoing="_NWozIKyLEfGxAq-kOcKFjQ" incoming="__2C78KyKEfGxAq-kOcKFjQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_da59cqyKEfGxAq-kOcKFjQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_da59cayKEfGxAq-kOcKFjQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_da59c6yKEfGxAq-kOcKFjQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_da59dKyKEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_da59dayKEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_da59dqyKEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_da6kgKyKEfGxAq-kOcKFjQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_da59d6yKEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_ABZa6ayMEfGxAq-kOcKFjQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_ABZa6qyMEfGxAq-kOcKFjQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_ABZa6KyMEfGxAq-kOcKFjQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_ABZa66yMEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_I1vI4KyNEfGxAq-kOcKFjQ" name="Seleccionar ofertas" outgoing="_lIB9AKyREfGxAq-kOcKFjQ" incoming="_NWozIKyLEfGxAq-kOcKFjQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_DYThwayLEfGxAq-kOcKFjQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_DYThwKyLEfGxAq-kOcKFjQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_DYThwqyLEfGxAq-kOcKFjQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_DYThw6yLEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_DYThxKyLEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_DYThxayLEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_DYThx6yLEfGxAq-kOcKFjQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_DYThxqyLEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_I1vv86yNEfGxAq-kOcKFjQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_I1vv9KyNEfGxAq-kOcKFjQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_I1vv8qyNEfGxAq-kOcKFjQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_I1vv9ayNEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_lIAu4KyREfGxAq-kOcKFjQ" name="Procesar adjudicacion" outgoing="_5RA58KyQEfGxAq-kOcKFjQ _HSuEsKySEfGxAq-kOcKFjQ" incoming="_lIB9AKyREfGxAq-kOcKFjQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_lIAu4qyREfGxAq-kOcKFjQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_lIAu4ayREfGxAq-kOcKFjQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_lIAu46yREfGxAq-kOcKFjQ" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_nFnesKfpEfGZSb5q5b0p5g" name="Centro coordinador">
        <elements xmi:type="process:Task" xmi:id="_91GHUKfpEfGZSb5q5b0p5g" name="Generar y publicar lotes" outgoing="__D9uMKfpEfGZSb5q5b0p5g" incoming="_-b1XMKfpEfGZSb5q5b0p5g" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_91HVcafpEfGZSb5q5b0p5g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_91HVcKfpEfGZSb5q5b0p5g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_91HVcqfpEfGZSb5q5b0p5g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_91HVc6fpEfGZSb5q5b0p5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_91HVdKfpEfGZSb5q5b0p5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_91HVdafpEfGZSb5q5b0p5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_91HVd6fpEfGZSb5q5b0p5g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_91HVdqfpEfGZSb5q5b0p5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_91H8gKfpEfGZSb5q5b0p5g">
            <targetForm xmi:type="expression:Expression" xmi:id="_91H8gafpEfGZSb5q5b0p5g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_91HVeKfpEfGZSb5q5b0p5g"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_91H8gqfpEfGZSb5q5b0p5g" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_ODwuUKfqEfGZSb5q5b0p5g" name="recibir ofertas" outgoing="_okNm0KftEfGZSb5q5b0p5g" incoming="_d_E0IKftEfGZSb5q5b0p5g" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ODyjgafqEfGZSb5q5b0p5g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ODyjgKfqEfGZSb5q5b0p5g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ODyjgqfqEfGZSb5q5b0p5g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_ODyjg6fqEfGZSb5q5b0p5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_ODyjhKfqEfGZSb5q5b0p5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_ODyjhafqEfGZSb5q5b0p5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_ODyjh6fqEfGZSb5q5b0p5g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_ODyjhqfqEfGZSb5q5b0p5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <BoundaryIntermediateEvents xmi:type="process:BoundaryTimerEvent" xmi:id="_A_SEAKftEfGZSb5q5b0p5g" name="Fin ventana convocatoria" outgoing="_rsFlowTimerToValid">
            <condition xmi:type="expression:Expression" xmi:id="_rsTimerCond" name="3600000" content="3600000" type="TYPE_CONSTANT" returnType="java.lang.Long" returnTypeFixed="true"/>
          </BoundaryIntermediateEvents>
          <formMapping xmi:type="process:FormMapping" xmi:id="_ODyjiafqEfGZSb5q5b0p5g">
            <targetForm xmi:type="expression:Expression" xmi:id="_ODyjiqfqEfGZSb5q5b0p5g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_ODyjiKfqEfGZSb5q5b0p5g">
            <inputs xmi:type="process:ContractInput" xmi:id="_rsContractInputLotes" name="lotesCubiertos" type="BOOLEAN" description="Decision del Centro Coordinador: indica si los lotes de necesidades quedaron cubiertos">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_rsContractMapping" data="_rsDataLotesCubiertos"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_ODyji6fqEfGZSb5q5b0p5g" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_SNfgoKfmEfGZSb5q5b0p5g" name="Lotes cubiertos?" outgoing="_uLFvwKftEfGZSb5q5b0p5g _AZL34KfuEfGZSb5q5b0p5g" incoming="_okNm0KftEfGZSb5q5b0p5g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_SNsU8KfmEfGZSb5q5b0p5g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_SNrG0KfmEfGZSb5q5b0p5g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_SNsU8afmEfGZSb5q5b0p5g" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_3iFyoKyTEfGxAq-kOcKFjQ" name="Adjudicacion completa" outgoing="_YcuLMayVEfGxAq-kOcKFjQ" incoming="_5rlOsKyTEfGxAq-kOcKFjQ _6VJwIKyTEfGxAq-kOcKFjQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_3iFyoqyTEfGxAq-kOcKFjQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_3iFyoayTEfGxAq-kOcKFjQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_3iFyo6yTEfGxAq-kOcKFjQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_Zu9ZsKyWEfGxAq-kOcKFjQ" name="Monitorear despliegue" outgoing="_jlARwKyWEfGxAq-kOcKFjQ" incoming="_YcuLMayVEfGxAq-kOcKFjQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_YctkIqyVEfGxAq-kOcKFjQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_YctkIayVEfGxAq-kOcKFjQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_YctkI6yVEfGxAq-kOcKFjQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_YctkJKyVEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_YctkJayVEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_YctkJqyVEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_YctkKKyVEfGxAq-kOcKFjQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_YctkJ6yVEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_Zu9ZuqyWEfGxAq-kOcKFjQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_Zu9Zu6yWEfGxAq-kOcKFjQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_Zu9ZuayWEfGxAq-kOcKFjQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_Zu9ZvKyWEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_ZqAy0KyXEfGxAq-kOcKFjQ" name="Cerrar operativo" outgoing="_kanOoKyXEfGxAq-kOcKFjQ" incoming="_byGgsKyXEfGxAq-kOcKFjQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ZqBZ4ayXEfGxAq-kOcKFjQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ZqBZ4KyXEfGxAq-kOcKFjQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ZqBZ4qyXEfGxAq-kOcKFjQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_ZqBZ46yXEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_ZqBZ5KyXEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_ZqBZ5ayXEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_ZqBZ56yXEfGxAq-kOcKFjQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_ZqBZ5qyXEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_ZqBZ6ayXEfGxAq-kOcKFjQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_ZqBZ6qyXEfGxAq-kOcKFjQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_ZqBZ6KyXEfGxAq-kOcKFjQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_ZqBZ66yXEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_jcCGgKyXEfGxAq-kOcKFjQ" name="Finalizacion" incoming="_kanOoKyXEfGxAq-kOcKFjQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_jcCtkayXEfGxAq-kOcKFjQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_jcCtkKyXEfGxAq-kOcKFjQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_jcCtkqyXEfGxAq-kOcKFjQ" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_gVcV8KfqEfGZSb5q5b0p5g" name="ONG">
        <elements xmi:type="process:Task" xmi:id="_cGp58KftEfGZSb5q5b0p5g" name="Enviar Oferta" outgoing="_d_E0IKftEfGZSb5q5b0p5g" incoming="__D9uMKfpEfGZSb5q5b0p5g _uLFvwKftEfGZSb5q5b0p5g" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_cGxOsKftEfGZSb5q5b0p5g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_cGwnoKftEfGZSb5q5b0p5g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_cGx1wKftEfGZSb5q5b0p5g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_cGx1waftEfGZSb5q5b0p5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_cGx1wqftEfGZSb5q5b0p5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_cGx1w6ftEfGZSb5q5b0p5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_cGx1xaftEfGZSb5q5b0p5g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_cGx1xKftEfGZSb5q5b0p5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_cGx1x6ftEfGZSb5q5b0p5g">
            <targetForm xmi:type="expression:Expression" xmi:id="_cGx1yKftEfGZSb5q5b0p5g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_cGx1xqftEfGZSb5q5b0p5g"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_cGx1yaftEfGZSb5q5b0p5g" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_NravUKyWEfGxAq-kOcKFjQ" name="Visualizar notificacion" outgoing="_5rlOsKyTEfGxAq-kOcKFjQ" incoming="_5RA58KyQEfGxAq-kOcKFjQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_iW5uoayQEfGxAq-kOcKFjQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_iW5uoKyQEfGxAq-kOcKFjQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_iW5uoqyQEfGxAq-kOcKFjQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_iW5uo6yQEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_iW5upKyQEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_iW5upayQEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_iW5up6yQEfGxAq-kOcKFjQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_iW5upqyQEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_NrbWaayWEfGxAq-kOcKFjQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_NrbWaqyWEfGxAq-kOcKFjQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_NrbWaKyWEfGxAq-kOcKFjQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_NrbWa6yWEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_iL-CQKyWEfGxAq-kOcKFjQ" name="Marcar actividad finalizada" outgoing="_otVdgKyWEfGxAq-kOcKFjQ" incoming="_jlARwKyWEfGxAq-kOcKFjQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_iL-pUayWEfGxAq-kOcKFjQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_iL-pUKyWEfGxAq-kOcKFjQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_iL-pUqyWEfGxAq-kOcKFjQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_iL-pU6yWEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_iL-pVKyWEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_iL-pVayWEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_iL-pV6yWEfGxAq-kOcKFjQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_iL-pVqyWEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_iL-pWayWEfGxAq-kOcKFjQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_iL-pWqyWEfGxAq-kOcKFjQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_iL-pWKyWEfGxAq-kOcKFjQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_iL-pW6yWEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_r-AG0KflEfGZSb5q5b0p5g">
        <targetForm xmi:type="expression:Expression" xmi:id="_r-AG0aflEfGZSb5q5b0p5g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_r-AG0qflEfGZSb5q5b0p5g">
        <targetForm xmi:type="expression:Expression" xmi:id="_r-AG06flEfGZSb5q5b0p5g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_r-AG1KflEfGZSb5q5b0p5g" target="_r-AGw6flEfGZSb5q5b0p5g" source="_r9_fsqflEfGZSb5q5b0p5g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_r-AG1aflEfGZSb5q5b0p5g"/>
        <condition xmi:type="expression:Expression" xmi:id="_r-AG1qflEfGZSb5q5b0p5g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_-b1XMKfpEfGZSb5q5b0p5g" target="_91GHUKfpEfGZSb5q5b0p5g" source="_r-AGw6flEfGZSb5q5b0p5g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_-b1-QKfpEfGZSb5q5b0p5g"/>
        <condition xmi:type="expression:Expression" xmi:id="_-b1-QafpEfGZSb5q5b0p5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="__D9uMKfpEfGZSb5q5b0p5g" target="_cGp58KftEfGZSb5q5b0p5g" source="_91GHUKfpEfGZSb5q5b0p5g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="__D_jYKfpEfGZSb5q5b0p5g"/>
        <condition xmi:type="expression:Expression" xmi:id="__EAKcKfpEfGZSb5q5b0p5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_d_E0IKftEfGZSb5q5b0p5g" target="_ODwuUKfqEfGZSb5q5b0p5g" source="_cGp58KftEfGZSb5q5b0p5g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_d_GpUKftEfGZSb5q5b0p5g"/>
        <condition xmi:type="expression:Expression" xmi:id="_d_GpUaftEfGZSb5q5b0p5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_okNm0KftEfGZSb5q5b0p5g" target="_SNfgoKfmEfGZSb5q5b0p5g" source="_ODwuUKfqEfGZSb5q5b0p5g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_okPcAKftEfGZSb5q5b0p5g"/>
        <condition xmi:type="expression:Expression" xmi:id="_okPcAaftEfGZSb5q5b0p5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_uLFvwKftEfGZSb5q5b0p5g" name="No" target="_cGp58KftEfGZSb5q5b0p5g" source="_SNfgoKfmEfGZSb5q5b0p5g" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_uLJaIKftEfGZSb5q5b0p5g"/>
        <condition xmi:type="expression:Expression" xmi:id="_uLKBMKftEfGZSb5q5b0p5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_AZL34KfuEfGZSb5q5b0p5g" name="si" target="__CbgUKftEfGZSb5q5b0p5g" source="_SNfgoKfmEfGZSb5q5b0p5g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_AZNtEKfuEfGZSb5q5b0p5g"/>
        <condition xmi:type="expression:Expression" xmi:id="_AZNtEafuEfGZSb5q5b0p5g" name="lotesCubiertos" content="lotesCubiertos" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_rsRefLotesSi" name="lotesCubiertos" dataType="_r-AG6KflEfGZSb5q5b0p5g">
            <defaultValue xmi:type="expression:Expression" xmi:id="_rsRefLotesSiDef" name="false" content="false" type="TYPE_CONSTANT" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          </referencedElements>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_rsFlowTimerToValid" name="ventana vencida" target="__CbgUKftEfGZSb5q5b0p5g" source="_A_SEAKftEfGZSb5q5b0p5g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_rsFlowTimerDT"/>
        <condition xmi:type="expression:Expression" xmi:id="_rsFlowTimerCond" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_LBHisKyKEfGxAq-kOcKFjQ" target="__h1KAKyLEfGxAq-kOcKFjQ" source="__CbgUKftEfGZSb5q5b0p5g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_LBHisayKEfGxAq-kOcKFjQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_LBHisqyKEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="__2C78KyKEfGxAq-kOcKFjQ" target="_ABYz0KyMEfGxAq-kOcKFjQ" source="__h1KAKyLEfGxAq-kOcKFjQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="__2C78ayKEfGxAq-kOcKFjQ"/>
        <condition xmi:type="expression:Expression" xmi:id="__2C78qyKEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_NWozIKyLEfGxAq-kOcKFjQ" target="_I1vI4KyNEfGxAq-kOcKFjQ" source="_ABYz0KyMEfGxAq-kOcKFjQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_NWozIayLEfGxAq-kOcKFjQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_NWozIqyLEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_5RA58KyQEfGxAq-kOcKFjQ" target="_NravUKyWEfGxAq-kOcKFjQ" source="_lIAu4KyREfGxAq-kOcKFjQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_5RA58ayQEfGxAq-kOcKFjQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_5RA58qyQEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_lIB9AKyREfGxAq-kOcKFjQ" target="_lIAu4KyREfGxAq-kOcKFjQ" source="_I1vI4KyNEfGxAq-kOcKFjQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_lIB9AayREfGxAq-kOcKFjQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_lIB9AqyREfGxAq-kOcKFjQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_HSuEsKySEfGxAq-kOcKFjQ" target="_zfop0KyTEfGxAq-kOcKFjQ" source="_lIAu4KyREfGxAq-kOcKFjQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_HSuEsaySEfGxAq-kOcKFjQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_HSurwKySEfGxAq-kOcKFjQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_5rlOsKyTEfGxAq-kOcKFjQ" target="_3iFyoKyTEfGxAq-kOcKFjQ" source="_NravUKyWEfGxAq-kOcKFjQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_5rlOsayTEfGxAq-kOcKFjQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_5rlOsqyTEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_6VJwIKyTEfGxAq-kOcKFjQ" target="_3iFyoKyTEfGxAq-kOcKFjQ" source="_zfop0KyTEfGxAq-kOcKFjQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_6VJwIayTEfGxAq-kOcKFjQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_6VJwIqyTEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_YcuLMayVEfGxAq-kOcKFjQ" target="_Zu9ZsKyWEfGxAq-kOcKFjQ" source="_3iFyoKyTEfGxAq-kOcKFjQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_YcuLMqyVEfGxAq-kOcKFjQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_YcuLM6yVEfGxAq-kOcKFjQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_jlARwKyWEfGxAq-kOcKFjQ" target="_iL-CQKyWEfGxAq-kOcKFjQ" source="_Zu9ZsKyWEfGxAq-kOcKFjQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_jlARwayWEfGxAq-kOcKFjQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_jlARwqyWEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_otVdgKyWEfGxAq-kOcKFjQ" target="_C1-aUKyXEfGxAq-kOcKFjQ" source="_iL-CQKyWEfGxAq-kOcKFjQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_otWEkKyWEfGxAq-kOcKFjQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_otWEkayWEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_HybtQKyXEfGxAq-kOcKFjQ" target="_GjEXIKyXEfGxAq-kOcKFjQ" source="_C1-aUKyXEfGxAq-kOcKFjQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_HybtQayXEfGxAq-kOcKFjQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_HybtQqyXEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_byGgsKyXEfGxAq-kOcKFjQ" target="_ZqAy0KyXEfGxAq-kOcKFjQ" source="_GjEXIKyXEfGxAq-kOcKFjQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_byGgsayXEfGxAq-kOcKFjQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_byGgsqyXEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kanOoKyXEfGxAq-kOcKFjQ" target="_jcCGgKyXEfGxAq-kOcKFjQ" source="_ZqAy0KyXEfGxAq-kOcKFjQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kanOoayXEfGxAq-kOcKFjQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_kanOoqyXEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <data xmi:type="process:Data" xmi:id="_rsDataLotesCubiertos" name="lotesCubiertos" dataType="_r-AG6KflEfGZSb5q5b0p5g">
        <defaultValue xmi:type="expression:Expression" xmi:id="_rsDefaultLotes" name="false" content="false" type="TYPE_CONSTANT" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </data>
      <actors xmi:type="process:Actor" xmi:id="_r-AG16flEfGZSb5q5b0p5g" documentation="This is an example of actor that is mapped to any ACME users" name="Employee actor" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_XDEoIKfpEfGZSb5q5b0p5g" name="Municipio"/>
      <contract xmi:type="process:Contract" xmi:id="_r-AG2KflEfGZSb5q5b0p5g"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_r-AG2aflEfGZSb5q5b0p5g">
        <name xmi:type="expression:Expression" xmi:id="_r-AG2qflEfGZSb5q5b0p5g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_r-AG26flEfGZSb5q5b0p5g" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_r-AG3KflEfGZSb5q5b0p5g">
        <name xmi:type="expression:Expression" xmi:id="_r-AG3aflEfGZSb5q5b0p5g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_r-AG3qflEfGZSb5q5b0p5g" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_r-AG36flEfGZSb5q5b0p5g">
        <name xmi:type="expression:Expression" xmi:id="_r-AG4KflEfGZSb5q5b0p5g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_r-AG4aflEfGZSb5q5b0p5g" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_r-AG4qflEfGZSb5q5b0p5g">
        <name xmi:type="expression:Expression" xmi:id="_r-AG46flEfGZSb5q5b0p5g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_r-AG5KflEfGZSb5q5b0p5g" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_r-AG5aflEfGZSb5q5b0p5g">
        <name xmi:type="expression:Expression" xmi:id="_r-AG5qflEfGZSb5q5b0p5g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_r-AG56flEfGZSb5q5b0p5g" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_r-AG6KflEfGZSb5q5b0p5g" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_r-AG6aflEfGZSb5q5b0p5g" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_r-AG6qflEfGZSb5q5b0p5g" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_r-AG66flEfGZSb5q5b0p5g" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_r-AG7KflEfGZSb5q5b0p5g" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_r-AG7aflEfGZSb5q5b0p5g" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_r-AG7qflEfGZSb5q5b0p5g" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_r-AG76flEfGZSb5q5b0p5g" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_r-AG8KflEfGZSb5q5b0p5g" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_r-AG8aflEfGZSb5q5b0p5g" type="Process" element="_r9-4oKflEfGZSb5q5b0p5g" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_r-AG8qflEfGZSb5q5b0p5g" type="2007" element="_r9_fsKflEfGZSb5q5b0p5g">
      <children xmi:type="notation:DecorationNode" xmi:id="_r-At0KflEfGZSb5q5b0p5g" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_r-At0aflEfGZSb5q5b0p5g" type="7001">
        <children xmi:type="notation:Node" xmi:id="_r-At0qflEfGZSb5q5b0p5g" type="3007" element="_r9_fsaflEfGZSb5q5b0p5g">
          <children xmi:type="notation:DecorationNode" xmi:id="_r-At06flEfGZSb5q5b0p5g" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_r-At1KflEfGZSb5q5b0p5g" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_r-At1aflEfGZSb5q5b0p5g" type="3005" element="_r-AGw6flEfGZSb5q5b0p5g" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_r-At1qflEfGZSb5q5b0p5g" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_r-At16flEfGZSb5q5b0p5g" x="160" y="60" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_r-At2KflEfGZSb5q5b0p5g" type="3002" element="_r9_fsqflEfGZSb5q5b0p5g" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_r-At2aflEfGZSb5q5b0p5g" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_r-At2qflEfGZSb5q5b0p5g" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_r-At26flEfGZSb5q5b0p5g" x="63" y="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ABaB8KyMEfGxAq-kOcKFjQ" type="3005" element="_ABYz0KyMEfGxAq-kOcKFjQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ABaB8qyMEfGxAq-kOcKFjQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ABaB8ayMEfGxAq-kOcKFjQ" x="1049" y="119" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_I1vv9qyNEfGxAq-kOcKFjQ" type="3005" element="_I1vI4KyNEfGxAq-kOcKFjQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_I1vv-KyNEfGxAq-kOcKFjQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_I1vv96yNEfGxAq-kOcKFjQ" x="1353" y="124" width="109" height="54"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_lIBV8KyREfGxAq-kOcKFjQ" type="3009" element="_lIAu4KyREfGxAq-kOcKFjQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_lIBV8qyREfGxAq-kOcKFjQ" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_lIBV86yREfGxAq-kOcKFjQ" x="23" y="6"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_lIBV8ayREfGxAq-kOcKFjQ" x="1541" y="142"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_r-At3KflEfGZSb5q5b0p5g"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_r-At3aflEfGZSb5q5b0p5g" fontName=".AppleSystemUIFont"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_r-At3qflEfGZSb5q5b0p5g"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_r-At36flEfGZSb5q5b0p5g"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_r-At4KflEfGZSb5q5b0p5g"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_nFsXMKfpEfGZSb5q5b0p5g" type="3007" element="_nFnesKfpEfGZSb5q5b0p5g">
          <children xmi:type="notation:DecorationNode" xmi:id="_nFwooKfpEfGZSb5q5b0p5g" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_nFxPsKfpEfGZSb5q5b0p5g" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_91ODIKfpEfGZSb5q5b0p5g" type="3005" element="_91GHUKfpEfGZSb5q5b0p5g" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_91OqMKfpEfGZSb5q5b0p5g" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_91ODIafpEfGZSb5q5b0p5g" x="343" y="112" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_OD4qIKfqEfGZSb5q5b0p5g" type="3005" element="_ODwuUKfqEfGZSb5q5b0p5g" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_OD54QKfqEfGZSb5q5b0p5g" type="5005"/>
              <children xmi:type="notation:Shape" xmi:id="_A_lmAKftEfGZSb5q5b0p5g" type="3043" element="_A_SEAKftEfGZSb5q5b0p5g" fontName=".AppleSystemUIFont">
                <children xmi:type="notation:DecorationNode" xmi:id="_A_opUKftEfGZSb5q5b0p5g" type="5055">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="_A_opUaftEfGZSb5q5b0p5g" y="5"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_A_lmAaftEfGZSb5q5b0p5g" x="95" y="-17"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_OD4qIafqEfGZSb5q5b0p5g" x="553" y="112" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_SN1e4KfmEfGZSb5q5b0p5g" type="3008" element="_SNfgoKfmEfGZSb5q5b0p5g" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_SN5JQKfmEfGZSb5q5b0p5g" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_SN5JQafmEfGZSb5q5b0p5g" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SN2tAKfmEfGZSb5q5b0p5g" x="821" y="28"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_3iGZsKyTEfGxAq-kOcKFjQ" type="3009" element="_3iFyoKyTEfGxAq-kOcKFjQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_3iGZsqyTEfGxAq-kOcKFjQ" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_3iHAwKyTEfGxAq-kOcKFjQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_3iGZsayTEfGxAq-kOcKFjQ" x="1714" y="28"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Zu9ZvayWEfGxAq-kOcKFjQ" type="3005" element="_Zu9ZsKyWEfGxAq-kOcKFjQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Zu9Zv6yWEfGxAq-kOcKFjQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Zu9ZvqyWEfGxAq-kOcKFjQ" x="1950" y="41" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ZqCA8KyXEfGxAq-kOcKFjQ" type="3005" element="_ZqAy0KyXEfGxAq-kOcKFjQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ZqCA8qyXEfGxAq-kOcKFjQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ZqCA8ayXEfGxAq-kOcKFjQ" x="2285" y="70" width="130" height="65"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_jcDUoKyXEfGxAq-kOcKFjQ" type="3003" element="_jcCGgKyXEfGxAq-kOcKFjQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_jcDUoqyXEfGxAq-kOcKFjQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_jcDUo6yXEfGxAq-kOcKFjQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_jcDUoayXEfGxAq-kOcKFjQ" x="2550" y="88"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_nFsXMafpEfGZSb5q5b0p5g"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_nFsXMqfpEfGZSb5q5b0p5g" fontName=".AppleSystemUIFont"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_nFsXM6fpEfGZSb5q5b0p5g"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_nFxPsafpEfGZSb5q5b0p5g"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_nFsXNKfpEfGZSb5q5b0p5g" x="231" y="185"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_gVq_cKfqEfGZSb5q5b0p5g" type="3007" element="_gVcV8KfqEfGZSb5q5b0p5g">
          <children xmi:type="notation:DecorationNode" xmi:id="_gVv38KfqEfGZSb5q5b0p5g" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_gVwfAKfqEfGZSb5q5b0p5g" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_cG1gIKftEfGZSb5q5b0p5g" type="3005" element="_cGp58KftEfGZSb5q5b0p5g" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_cG3VUKftEfGZSb5q5b0p5g" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_cG1gIaftEfGZSb5q5b0p5g" x="573" y="33"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_NrbWbKyWEfGxAq-kOcKFjQ" type="3005" element="_NravUKyWEfGxAq-kOcKFjQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Nrb9cKyWEfGxAq-kOcKFjQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_NrbWbayWEfGxAq-kOcKFjQ" x="1191" y="40" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_iL-pXKyWEfGxAq-kOcKFjQ" type="3005" element="_iL-CQKyWEfGxAq-kOcKFjQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_iL_QYKyWEfGxAq-kOcKFjQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_iL-pXayWEfGxAq-kOcKFjQ" x="1950" y="59" width="120" height="60"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_gVrmgKfqEfGZSb5q5b0p5g"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_gVsNkKfqEfGZSb5q5b0p5g" fontName=".AppleSystemUIFont"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_gVsNkafqEfGZSb5q5b0p5g"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_gVwfAafqEfGZSb5q5b0p5g"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_gVsNkqfqEfGZSb5q5b0p5g" x="23" y="652" width="2497" height="179"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_7YBrIKftEfGZSb5q5b0p5g" type="3007" element="_7XVHkKftEfGZSb5q5b0p5g">
          <children xmi:type="notation:DecorationNode" xmi:id="_7YF8kKftEfGZSb5q5b0p5g" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_7YGjoKftEfGZSb5q5b0p5g" type="7002">
            <children xmi:type="notation:Shape" xmi:id="__CgY0KftEfGZSb5q5b0p5g" type="3027" element="__CbgUKftEfGZSb5q5b0p5g" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="__Cg_4KftEfGZSb5q5b0p5g" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="__CgY0aftEfGZSb5q5b0p5g" x="805" y="25" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="__h1xGKyLEfGxAq-kOcKFjQ" type="3027" element="__h1KAKyLEfGxAq-kOcKFjQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="__h1xGqyLEfGxAq-kOcKFjQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="__h1xGayLEfGxAq-kOcKFjQ" x="1070" y="30" width="122" height="61"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_zfpQ4KyTEfGxAq-kOcKFjQ" type="3027" element="_zfop0KyTEfGxAq-kOcKFjQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_zfpQ4qyTEfGxAq-kOcKFjQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_zfpQ4ayTEfGxAq-kOcKFjQ" x="1513" y="41" width="130" height="65"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_C1_BaKyXEfGxAq-kOcKFjQ" type="3027" element="_C1-aUKyXEfGxAq-kOcKFjQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_C1_BaqyXEfGxAq-kOcKFjQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_C1_BaayXEfGxAq-kOcKFjQ" x="2037" y="84" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_GjE-MKyXEfGxAq-kOcKFjQ" type="3027" element="_GjEXIKyXEfGxAq-kOcKFjQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_GjE-MqyXEfGxAq-kOcKFjQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_GjE-MayXEfGxAq-kOcKFjQ" x="2284" y="89" width="132" height="66"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_7YCSMKftEfGZSb5q5b0p5g"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_7YCSMaftEfGZSb5q5b0p5g" fontName=".AppleSystemUIFont"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_7YCSMqftEfGZSb5q5b0p5g"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_7YGjoaftEfGZSb5q5b0p5g"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_7YCSM6ftEfGZSb5q5b0p5g" x="23" y="10" width="2497" height="215"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_r-At4aflEfGZSb5q5b0p5g"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_r-At4qflEfGZSb5q5b0p5g" fontName=".AppleSystemUIFont"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_r-At46flEfGZSb5q5b0p5g"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_r-At5KflEfGZSb5q5b0p5g"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_r-At5aflEfGZSb5q5b0p5g" width="2670" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_r-At5qflEfGZSb5q5b0p5g"/>
    <edges xmi:type="notation:Connector" xmi:id="_r-At56flEfGZSb5q5b0p5g" type="4001" element="_r-AG1KflEfGZSb5q5b0p5g" source="_r-At2KflEfGZSb5q5b0p5g" target="_r-At1aflEfGZSb5q5b0p5g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_r-At6KflEfGZSb5q5b0p5g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_r-At6aflEfGZSb5q5b0p5g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_r-At6qflEfGZSb5q5b0p5g" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_r-At66flEfGZSb5q5b0p5g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_-b5BkKfpEfGZSb5q5b0p5g" type="4001" element="_-b1XMKfpEfGZSb5q5b0p5g" source="_r-At1aflEfGZSb5q5b0p5g" target="_91ODIKfpEfGZSb5q5b0p5g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_-b5ooKfpEfGZSb5q5b0p5g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_-b5ooafpEfGZSb5q5b0p5g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_-b5BkafpEfGZSb5q5b0p5g" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_-b5BkqfpEfGZSb5q5b0p5g" points="[5, 12, -104, -267]$[103, 270, -6, -9]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_-b_vQKfpEfGZSb5q5b0p5g" id="(0.9583333333333334,0.5333333333333333)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_-cAWUKfpEfGZSb5q5b0p5g" id="(0.41,0.18)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="__EB_oKfpEfGZSb5q5b0p5g" type="4001" element="__D9uMKfpEfGZSb5q5b0p5g" source="_91ODIKfpEfGZSb5q5b0p5g" target="_cG1gIKftEfGZSb5q5b0p5g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="__ECmsKfpEfGZSb5q5b0p5g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="__ECmsafpEfGZSb5q5b0p5g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="__EB_oafpEfGZSb5q5b0p5g" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="__EB_oqfpEfGZSb5q5b0p5g" points="[0, 30, 0, -200]$[0, 220, 0, -10]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="__ED00KfpEfGZSb5q5b0p5g" id="(0.5,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="__ED00Target" id="(0.5,0.0)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_d_JsoKftEfGZSb5q5b0p5g" type="4001" element="_d_E0IKftEfGZSb5q5b0p5g" source="_cG1gIKftEfGZSb5q5b0p5g" target="_OD4qIKfqEfGZSb5q5b0p5g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_d_Lh0KftEfGZSb5q5b0p5g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_d_Lh0aftEfGZSb5q5b0p5g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_d_JsoaftEfGZSb5q5b0p5g" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_d_KTsKftEfGZSb5q5b0p5g" points="[-1, -25, 0, 118]$[1, -136, 2, 7]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_d_Wg8KftEfGZSb5q5b0p5g" id="(0.575,0.8833333333333333)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_okR4QKftEfGZSb5q5b0p5g" type="4001" element="_okNm0KftEfGZSb5q5b0p5g" source="_OD4qIKfqEfGZSb5q5b0p5g" target="_SN1e4KfmEfGZSb5q5b0p5g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_okTtcKftEfGZSb5q5b0p5g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_okTtcaftEfGZSb5q5b0p5g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_okSfUKftEfGZSb5q5b0p5g" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_okSfUaftEfGZSb5q5b0p5g" points="[19, -9, -181, 91]$[200, -9, 0, 91]$[200, -78, 0, 22]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_okZ0EKftEfGZSb5q5b0p5g" id="(0.8416666666666667,0.6166666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_uMIRkKftEfGZSb5q5b0p5g" type="4001" element="_uLFvwKftEfGZSb5q5b0p5g" source="_SN1e4KfmEfGZSb5q5b0p5g" target="_cG1gIKftEfGZSb5q5b0p5g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_uMI4oKftEfGZSb5q5b0p5g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_uMI4oaftEfGZSb5q5b0p5g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_uMIRkaftEfGZSb5q5b0p5g" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_uMIRkqftEfGZSb5q5b0p5g" points="[-10, 20, 200, -100]$[-200, 200, 10, 80]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_uML78KftEfGZSb5q5b0p5g" id="(0.1,0.8)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_uML78aftEfGZSb5q5b0p5g" id="(0.8,0.2)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AZidMKfuEfGZSb5q5b0p5g" type="4001" element="_AZL34KfuEfGZSb5q5b0p5g" source="_SN1e4KfmEfGZSb5q5b0p5g" target="__CgY0KftEfGZSb5q5b0p5g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_AZjEQKfuEfGZSb5q5b0p5g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_AZjEQafuEfGZSb5q5b0p5g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_AZidMafuEfGZSb5q5b0p5g" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AZidMqfuEfGZSb5q5b0p5g" points="[7, -7, 16, 296]$[-8, -311, 1, -8]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AZmuoKfuEfGZSb5q5b0p5g" id="(0.2558139534883721,0.23255813953488372)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AZmuoafuEfGZSb5q5b0p5g" id="(0.27,0.22)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_rsEdgeTimerValid" type="4001" element="_rsFlowTimerToValid" source="_A_lmAKftEfGZSb5q5b0p5g" target="__CgY0KftEfGZSb5q5b0p5g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_rsEdgeTimerValidLabel" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_rsEdgeTimerValidLabelLoc" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_rsEdgeTimerValidFont" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_rsEdgeTimerValidBP" points="[20, -10, -150, 50]$[160, -80, -10, -20]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_rsEdgeTimerValidSrc" id="(0.8,0.2)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_rsEdgeTimerValidTgt" id="(0.2,0.8)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_LBIJwKyKEfGxAq-kOcKFjQ" type="4001" element="_LBHisKyKEfGxAq-kOcKFjQ" source="__CgY0KftEfGZSb5q5b0p5g" target="__h1xGKyLEfGxAq-kOcKFjQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_LBIw0KyKEfGxAq-kOcKFjQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_LBIw0ayKEfGxAq-kOcKFjQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_LBIJwayKEfGxAq-kOcKFjQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_LBIJwqyKEfGxAq-kOcKFjQ" points="[0, -2, -149, 0]$[145, -2, -4, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_LBLNEKyKEfGxAq-kOcKFjQ" id="(1.0,0.5166666666666667)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_LBLNEayKEfGxAq-kOcKFjQ" id="(0.04,0.48)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="__2DjAKyKEfGxAq-kOcKFjQ" type="4001" element="__2C78KyKEfGxAq-kOcKFjQ" source="__h1xGKyLEfGxAq-kOcKFjQ" target="_ABaB8KyMEfGxAq-kOcKFjQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="__2DjA6yKEfGxAq-kOcKFjQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="__2DjBKyKEfGxAq-kOcKFjQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="__2DjAayKEfGxAq-kOcKFjQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="__2DjAqyKEfGxAq-kOcKFjQ" points="[3, 30, 0, -190]$[-12, 211, -15, -9]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="__2FYMKyKEfGxAq-kOcKFjQ" id="(0.225,0.15)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_NWpaMKyLEfGxAq-kOcKFjQ" type="4001" element="_NWozIKyLEfGxAq-kOcKFjQ" source="_ABaB8KyMEfGxAq-kOcKFjQ" target="_I1vv9qyNEfGxAq-kOcKFjQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_NWpaM6yLEfGxAq-kOcKFjQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_NWpaNKyLEfGxAq-kOcKFjQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_NWpaMayLEfGxAq-kOcKFjQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_NWpaMqyLEfGxAq-kOcKFjQ" points="[60, -1, -193, -2]$[244, -1, -9, -2]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_OFI34KyLEfGxAq-kOcKFjQ" id="(0.08256880733944955,0.48148148148148145)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_5RBhAKyQEfGxAq-kOcKFjQ" type="4001" element="_5RA58KyQEfGxAq-kOcKFjQ" source="_lIBV8KyREfGxAq-kOcKFjQ" target="_NrbWbKyWEfGxAq-kOcKFjQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_5RBhA6yQEfGxAq-kOcKFjQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_5RBhBKyQEfGxAq-kOcKFjQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_5RBhAayQEfGxAq-kOcKFjQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_5RBhAqyQEfGxAq-kOcKFjQ" points="[1, -5, 327, -370]$[1, 208, 327, -157]$[-277, 208, 49, -157]$[-277, 361, 49, -4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_l3z0IKyREfGxAq-kOcKFjQ" id="(0.23255813953488372,0.8604651162790697)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_5qTjsKyQEfGxAq-kOcKFjQ" id="(0.2833333333333333,0.06666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_lIB9A6yREfGxAq-kOcKFjQ" type="4001" element="_lIB9AKyREfGxAq-kOcKFjQ" source="_I1vv9qyNEfGxAq-kOcKFjQ" target="_lIBV8KyREfGxAq-kOcKFjQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_lIB9BqyREfGxAq-kOcKFjQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_lIB9B6yREfGxAq-kOcKFjQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_lIB9BKyREfGxAq-kOcKFjQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_lIB9BayREfGxAq-kOcKFjQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_HSurwaySEfGxAq-kOcKFjQ" type="4001" element="_HSuEsKySEfGxAq-kOcKFjQ" source="_lIBV8KyREfGxAq-kOcKFjQ" target="_zfpQ4KyTEfGxAq-kOcKFjQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_HSurxKySEfGxAq-kOcKFjQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_HSvS0KySEfGxAq-kOcKFjQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_HSurwqySEfGxAq-kOcKFjQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_HSurw6ySEfGxAq-kOcKFjQ" points="[-3, -18, 0, 212]$[-5, -224, -2, 6]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_HSwg8KySEfGxAq-kOcKFjQ" id="(0.46,0.88)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_5rlOs6yTEfGxAq-kOcKFjQ" type="4001" element="_5rlOsKyTEfGxAq-kOcKFjQ" source="_NrbWbKyWEfGxAq-kOcKFjQ" target="_3iGZsKyTEfGxAq-kOcKFjQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_5rl1wKyTEfGxAq-kOcKFjQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_5rl1wayTEfGxAq-kOcKFjQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_5rlOtKyTEfGxAq-kOcKFjQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_5rlOtayTEfGxAq-kOcKFjQ" points="[8, -7, -478, 389]$[484, -392, -2, 4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_5rnD4KyTEfGxAq-kOcKFjQ" id="(0.9333333333333333,0.5166666666666667)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_5rnD4ayTEfGxAq-kOcKFjQ" id="(0.3953488372093023,0.7674418604651163)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_6VKXMKyTEfGxAq-kOcKFjQ" type="4001" element="_6VJwIKyTEfGxAq-kOcKFjQ" source="_zfpQ4KyTEfGxAq-kOcKFjQ" target="_3iGZsKyTEfGxAq-kOcKFjQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_6VKXM6yTEfGxAq-kOcKFjQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_6VKXNKyTEfGxAq-kOcKFjQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_6VKXMayTEfGxAq-kOcKFjQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_6VKXMqyTEfGxAq-kOcKFjQ" points="[29, 10, -92, -367]$[119, 10, -2, -367]$[119, 358, -2, -19]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_6VLlUKyTEfGxAq-kOcKFjQ" id="(0.7769230769230769,0.5076923076923077)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_YcuLNKyVEfGxAq-kOcKFjQ" type="4001" element="_YcuLMayVEfGxAq-kOcKFjQ" source="_3iGZsKyTEfGxAq-kOcKFjQ" target="_Zu9ZvayWEfGxAq-kOcKFjQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_YcuLN6yVEfGxAq-kOcKFjQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_YcuLOKyVEfGxAq-kOcKFjQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_YcuLNayVEfGxAq-kOcKFjQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_YcuLNqyVEfGxAq-kOcKFjQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_jlA40KyWEfGxAq-kOcKFjQ" type="4001" element="_jlARwKyWEfGxAq-kOcKFjQ" source="_Zu9ZvayWEfGxAq-kOcKFjQ" target="_iL-pXKyWEfGxAq-kOcKFjQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_jlA406yWEfGxAq-kOcKFjQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_jlA41KyWEfGxAq-kOcKFjQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_jlA40ayWEfGxAq-kOcKFjQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_jlA40qyWEfGxAq-kOcKFjQ" points="[-2, 30, 8, -233]$[-12, 238, -2, -25]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_otWEkqyWEfGxAq-kOcKFjQ" type="4001" element="_otVdgKyWEfGxAq-kOcKFjQ" source="_iL-pXKyWEfGxAq-kOcKFjQ" target="_C1_BaKyXEfGxAq-kOcKFjQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_otWElayWEfGxAq-kOcKFjQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_otWElqyWEfGxAq-kOcKFjQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_otWEk6yWEfGxAq-kOcKFjQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_otWElKyWEfGxAq-kOcKFjQ" points="[17, 9, -17, 674]$[79, 9, 45, 674]$[79, -640, 45, 25]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_otXSsKyWEfGxAq-kOcKFjQ" id="(0.8583333333333333,0.35)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_r8ycEKyWEfGxAq-kOcKFjQ" id="(0.79,0.98)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_HycUUKyXEfGxAq-kOcKFjQ" type="4001" element="_HybtQKyXEfGxAq-kOcKFjQ" source="_C1_BaKyXEfGxAq-kOcKFjQ" target="_GjE-MKyXEfGxAq-kOcKFjQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_HycUU6yXEfGxAq-kOcKFjQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_HycUVKyXEfGxAq-kOcKFjQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_HycUUayXEfGxAq-kOcKFjQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_HycUUqyXEfGxAq-kOcKFjQ" points="[0, 6, -148, 6]$[127, 6, -21, 6]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_HydicKyXEfGxAq-kOcKFjQ" id="(1.0,0.5333333333333333)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_HydicayXEfGxAq-kOcKFjQ" id="(0.21,0.54)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_byHHwKyXEfGxAq-kOcKFjQ" type="4001" element="_byGgsKyXEfGxAq-kOcKFjQ" source="_GjE-MKyXEfGxAq-kOcKFjQ" target="_ZqCA8KyXEfGxAq-kOcKFjQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_byHHw6yXEfGxAq-kOcKFjQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_byHHxKyXEfGxAq-kOcKFjQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_byHHwayXEfGxAq-kOcKFjQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_byHHwqyXEfGxAq-kOcKFjQ" points="[1, 7, -31, -405]$[1, 202, -31, -210]$[9, 202, -23, -210]$[9, 387, -23, -25]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_byIV4KyXEfGxAq-kOcKFjQ" id="(0.42424242424242425,0.8939393939393939)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kan1sKyXEfGxAq-kOcKFjQ" type="4001" element="_kanOoKyXEfGxAq-kOcKFjQ" source="_ZqCA8KyXEfGxAq-kOcKFjQ" target="_jcDUoKyXEfGxAq-kOcKFjQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_kan1s6yXEfGxAq-kOcKFjQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kan1tKyXEfGxAq-kOcKFjQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kan1sayXEfGxAq-kOcKFjQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kan1sqyXEfGxAq-kOcKFjQ" points="[28, 8, -150, 6]$[177, 16, -1, 14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_kapD0KyXEfGxAq-kOcKFjQ" id="(0.7846153846153846,0.47692307692307695)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
