<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:decision="http://www.bonitasoft.org/ns/bpm/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/bpm/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/bpm/process">
  <process:MainProcess xmi:id="_r9-4oKflEfGZSb5q5b0p5g" name="MyDiagram" bonitaModelVersion="9">
    <elements xmi:type="process:Pool" xmi:id="_r9_fsKflEfGZSb5q5b0p5g" name="RescueSync" version="1.5">
      <elements xmi:type="process:Lane" xmi:id="_7XVHkKftEfGZSb5q5b0p5g" name="Sistema Nacional">
        <elements xmi:type="process:ServiceTask" xmi:id="__CbgUKftEfGZSb5q5b0p5g" name="Validacion de ofertas" outgoing="_jhaSALhZEfGBDbnOg0JlNw" incoming="_buZBoLhZEfGBDbnOg0JlNw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="__Cd8kaftEfGZSb5q5b0p5g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="__Cd8kKftEfGZSb5q5b0p5g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="__Cd8kqftEfGZSb5q5b0p5g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="__Cd8k6ftEfGZSb5q5b0p5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="__Cd8lKftEfGZSb5q5b0p5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="__Cd8laftEfGZSb5q5b0p5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="__Cd8l6ftEfGZSb5q5b0p5g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="__Cd8lqftEfGZSb5q5b0p5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_zfop0KyTEfGxAq-kOcKFjQ" name="Registrar compromiso de recursos" outgoing="_teKZkLhaEfGBDbnOg0JlNw" incoming="_rAgEULhaEfGBDbnOg0JlNw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_F0ZskaySEfGxAq-kOcKFjQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_F0ZskKySEfGxAq-kOcKFjQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_F0ZskqySEfGxAq-kOcKFjQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_F0Zsk6ySEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_F0ZslKySEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_F0ZslaySEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_F0Zsl6ySEfGxAq-kOcKFjQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_F0ZslqySEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_Dk1VwLhbEfGBDbnOg0JlNw" name="Hay cobertura?" outgoing="_kfpb4LhZEfGBDbnOg0JlNw _UpwEwLhaEfGBDbnOg0JlNw" incoming="_jhaSALhZEfGBDbnOg0JlNw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_fEUbobhZEfGBDbnOg0JlNw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_fEUboLhZEfGBDbnOg0JlNw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_fEUborhZEfGBDbnOg0JlNw" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_r9_fsaflEfGZSb5q5b0p5g" name="Municipio" actor="_XDEoIKfpEfGZSb5q5b0p5g">
        <elements xmi:type="process:StartEvent" xmi:id="_r9_fsqflEfGZSb5q5b0p5g" name="Ocurre emergencia" outgoing="_r-AG1KflEfGZSb5q5b0p5g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_r-AGwKflEfGZSb5q5b0p5g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_r-AGwaflEfGZSb5q5b0p5g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_r-AGwqflEfGZSb5q5b0p5g" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_r-AGw6flEfGZSb5q5b0p5g" name="Registrar emergencia" outgoing="_-b1XMKfpEfGZSb5q5b0p5g" incoming="_r-AG1KflEfGZSb5q5b0p5g" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_r-AGxKflEfGZSb5q5b0p5g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_r-AGxaflEfGZSb5q5b0p5g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_r-AGxqflEfGZSb5q5b0p5g" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_kjxJcK7uEfG2tZz6rNmRPQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_kjxJca7uEfG2tZz6rNmRPQ" name="emergenciaId" content="emergenciaId" type="TYPE_VARIABLE">
              <referencedElements xmi:type="process:Data" xmi:id="_mGKwUK7uEfG2tZz6rNmRPQ" name="emergenciaId" dataType="_r-AG7aflEfGZSb5q5b0p5g"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_kjxJcq7uEfG2tZz6rNmRPQ" name="emergenciaId" content="emergenciaId" type="TYPE_CONTRACT_INPUT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_qBc6IK7uEfG2tZz6rNmRPQ" name="emergenciaId">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_qBc6Ia7uEfG2tZz6rNmRPQ"/>
              </referencedElements>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_kjxJc67uEfG2tZz6rNmRPQ" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_r-AGx6flEfGZSb5q5b0p5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_r-AGyKflEfGZSb5q5b0p5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_r-AGyaflEfGZSb5q5b0p5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_r-AGyqflEfGZSb5q5b0p5g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_r-AGy6flEfGZSb5q5b0p5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_r-AGzKflEfGZSb5q5b0p5g">
            <targetForm xmi:type="expression:Expression" xmi:id="_N_aGEK96EfG2tZz6rNmRPQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_r-AGzqflEfGZSb5q5b0p5g">
            <inputs xmi:type="process:ContractInput" xmi:id="_fF814K7uEfG2tZz6rNmRPQ" name="emergenciaId">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_fF814a7uEfG2tZz6rNmRPQ"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_r-AGz6flEfGZSb5q5b0p5g" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_dEJeMLhaEfGBDbnOg0JlNw" name="Adjudicar y notificar a ONG" outgoing="_rAgEULhaEfGBDbnOg0JlNw" incoming="_UpwEwLhaEfGBDbnOg0JlNw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_PU0ncbhaEfGBDbnOg0JlNw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_PU0ncLhaEfGBDbnOg0JlNw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_PU0ncrhaEfGBDbnOg0JlNw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_PU0nc7haEfGBDbnOg0JlNw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_PU0ndLhaEfGBDbnOg0JlNw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_PU0ndbhaEfGBDbnOg0JlNw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_PU0nd7haEfGBDbnOg0JlNw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_PU0ndrhaEfGBDbnOg0JlNw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_nFnesKfpEfGZSb5q5b0p5g" name="Centro coordinador" actor="_CUNXYK7DEfGSsY55kcG7Og">
        <elements xmi:type="process:Task" xmi:id="_91GHUKfpEfGZSb5q5b0p5g" name="Generar y publicar lotes" outgoing="_KD-DwLhYEfGBDbnOg0JlNw" incoming="_-b1XMKfpEfGZSb5q5b0p5g _vjZIELhXEfGBDbnOg0JlNw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_91HVcafpEfGZSb5q5b0p5g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_91HVcKfpEfGZSb5q5b0p5g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_91HVcqfpEfGZSb5q5b0p5g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_91HVc6fpEfGZSb5q5b0p5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_91HVdKfpEfGZSb5q5b0p5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_91HVdafpEfGZSb5q5b0p5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_91HVd6fpEfGZSb5q5b0p5g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_91HVdqfpEfGZSb5q5b0p5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_91H8gKfpEfGZSb5q5b0p5g">
            <targetForm xmi:type="expression:Expression" xmi:id="_N_aGE696EfG2tZz6rNmRPQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_91HVeKfpEfGZSb5q5b0p5g"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_91H8gqfpEfGZSb5q5b0p5g" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_Zu9ZsKyWEfGxAq-kOcKFjQ" name="Monitorear despliegue" outgoing="_vDk4MLhaEfGBDbnOg0JlNw" incoming="_teKZkLhaEfGBDbnOg0JlNw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_YctkIqyVEfGxAq-kOcKFjQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_YctkIayVEfGxAq-kOcKFjQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_YctkI6yVEfGxAq-kOcKFjQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_YctkJKyVEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_YctkJayVEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_YctkJqyVEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_YctkKKyVEfGxAq-kOcKFjQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_YctkJ6yVEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_Zu9ZuqyWEfGxAq-kOcKFjQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_N_aGFK96EfG2tZz6rNmRPQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_Zu9ZuayWEfGxAq-kOcKFjQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_Zu9ZvKyWEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_jcCGgKyXEfGxAq-kOcKFjQ" name="Finalizacion" incoming="_9Ajl4LhZEfGBDbnOg0JlNw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_jcCtkayXEfGxAq-kOcKFjQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_jcCtkKyXEfGxAq-kOcKFjQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_jcCtkqyXEfGxAq-kOcKFjQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_pVRY8LhXEfGBDbnOg0JlNw" name="Evaluar curso alternativo" outgoing="_vjZIELhXEfGBDbnOg0JlNw" incoming="_kfpb4LhZEfGBDbnOg0JlNw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_pVcYEbhXEfGBDbnOg0JlNw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_pVcYELhXEfGBDbnOg0JlNw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_pVcYErhXEfGBDbnOg0JlNw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_pVcYE7hXEfGBDbnOg0JlNw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_pVcYFLhXEfGBDbnOg0JlNw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_pVcYFbhXEfGBDbnOg0JlNw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_pVc_ILhXEfGBDbnOg0JlNw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_pVcYFrhXEfGBDbnOg0JlNw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_gVcV8KfqEfGZSb5q5b0p5g" name="ONG" actor="_DVdZAK7DEfGSsY55kcG7Og">
        <elements xmi:type="process:Task" xmi:id="_iL-CQKyWEfGxAq-kOcKFjQ" name="Marcar actividad finalizada" outgoing="_9Ajl4LhZEfGBDbnOg0JlNw" incoming="_vDk4MLhaEfGBDbnOg0JlNw" type="PARALLEL" collectionDataToMultiInstantiate="__-ai4K79EfG2tZz6rNmRPQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_iL-pUayWEfGxAq-kOcKFjQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_iL-pUKyWEfGxAq-kOcKFjQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_iL-pUqyWEfGxAq-kOcKFjQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_iL-pU6yWEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_iL-pVKyWEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_iL-pVayWEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_iL-pV6yWEfGxAq-kOcKFjQ" name="ongUsuarioId" content="ongUsuarioId" type="MULTIINSTANCE_ITERATOR_TYPE" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_iL-pVqyWEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_iL-pWayWEfGxAq-kOcKFjQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_N_aGGK96EfG2tZz6rNmRPQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_iL-pWKyWEfGxAq-kOcKFjQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_iL-pW6yWEfGxAq-kOcKFjQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_-25VgK4eEfGSsY55kcG7Og" name="Obtener ofertas" outgoing="_buZBoLhZEfGBDbnOg0JlNw" incoming="_GiRCILhZEfGBDbnOg0JlNw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_-25Vgq4eEfGSsY55kcG7Og" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_-25Vga4eEfGSsY55kcG7Og" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_-25Vg64eEfGSsY55kcG7Og" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_-25VhK4eEfGSsY55kcG7Og" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_-25Vha4eEfGSsY55kcG7Og" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_-25Vhq4eEfGSsY55kcG7Og" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_-25ViK4eEfGSsY55kcG7Og" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_-25Vh64eEfGSsY55kcG7Og" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_8OycoLhXEfGBDbnOg0JlNw" name="Cargar o editar ofertas" outgoing="_GiRCILhZEfGBDbnOg0JlNw" incoming="_KD-DwLhYEfGBDbnOg0JlNw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_5ep3UbhXEfGBDbnOg0JlNw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_5ep3ULhXEfGBDbnOg0JlNw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_5ep3UrhXEfGBDbnOg0JlNw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_5ep3U7hXEfGBDbnOg0JlNw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_5ep3VLhXEfGBDbnOg0JlNw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_5ep3VbhXEfGBDbnOg0JlNw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_5ep3V7hXEfGBDbnOg0JlNw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_5ep3VrhXEfGBDbnOg0JlNw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <BoundaryIntermediateEvents xmi:type="process:BoundaryTimerEvent" xmi:id="_ZQNkcLhYEfGBDbnOg0JlNw" name="Tiempo limitado para subir ofertas"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_8OzDubhXEfGBDbnOg0JlNw">
            <targetForm xmi:type="expression:Expression" xmi:id="_8OzDurhXEfGBDbnOg0JlNw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_8OzDuLhXEfGBDbnOg0JlNw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_8OzDu7hXEfGBDbnOg0JlNw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:Data" xmi:id="_rsDataLotesCubiertos" name="lotesCubiertos" dataType="_r-AG6KflEfGZSb5q5b0p5g">
        <defaultValue xmi:type="expression:Expression" xmi:id="_rsDefaultLotes" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_XbgEwK7EEfGSsY55kcG7Og" name="cursoAccion" dataType="_r-AG7aflEfGZSb5q5b0p5g">
        <defaultValue xmi:type="expression:Expression" xmi:id="_XbgEwa7EEfGSsY55kcG7Og" content=""/>
      </data>
      <data xmi:type="process:Data" xmi:id="_LWBuoK7uEfG2tZz6rNmRPQ" name="emergenciaId" dataType="_r-AG7aflEfGZSb5q5b0p5g">
        <defaultValue xmi:type="expression:Expression" xmi:id="_LWBuoa7uEfG2tZz6rNmRPQ" content=""/>
      </data>
      <data xmi:type="process:Data" xmi:id="_lsQwoK7wEfG2tZz6rNmRPQ" name="convocatoriaActividadId" dataType="_r-AG7aflEfGZSb5q5b0p5g">
        <defaultValue xmi:type="expression:Expression" xmi:id="_lsQwoa7wEfG2tZz6rNmRPQ" content=""/>
      </data>
      <data xmi:type="process:Data" xmi:id="__-ai4K79EfG2tZz6rNmRPQ" name="ongDestinatarios" multiple="true" dataType="_r-AG7aflEfGZSb5q5b0p5g">
        <defaultValue xmi:type="expression:Expression" xmi:id="__-ai4a79EfG2tZz6rNmRPQ" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.List"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_r-AG0KflEfGZSb5q5b0p5g">
        <targetForm xmi:type="expression:Expression" xmi:id="_N_aGGa96EfG2tZz6rNmRPQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_r-AG0qflEfGZSb5q5b0p5g">
        <targetForm xmi:type="expression:Expression" xmi:id="_r-AG06flEfGZSb5q5b0p5g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_r-AG1KflEfGZSb5q5b0p5g" target="_r-AGw6flEfGZSb5q5b0p5g" source="_r9_fsqflEfGZSb5q5b0p5g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_r-AG1aflEfGZSb5q5b0p5g"/>
        <condition xmi:type="expression:Expression" xmi:id="_r-AG1qflEfGZSb5q5b0p5g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_-b1XMKfpEfGZSb5q5b0p5g" target="_91GHUKfpEfGZSb5q5b0p5g" source="_r-AGw6flEfGZSb5q5b0p5g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_-b1-QKfpEfGZSb5q5b0p5g"/>
        <condition xmi:type="expression:Expression" xmi:id="_-b1-QafpEfGZSb5q5b0p5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_vjZIELhXEfGBDbnOg0JlNw" target="_91GHUKfpEfGZSb5q5b0p5g" source="_pVRY8LhXEfGBDbnOg0JlNw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_vjZIEbhXEfGBDbnOg0JlNw"/>
        <condition xmi:type="expression:Expression" xmi:id="_vjZIErhXEfGBDbnOg0JlNw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_KD-DwLhYEfGBDbnOg0JlNw" target="_8OycoLhXEfGBDbnOg0JlNw" source="_91GHUKfpEfGZSb5q5b0p5g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_KD-DwbhYEfGBDbnOg0JlNw"/>
        <condition xmi:type="expression:Expression" xmi:id="_KD-DwrhYEfGBDbnOg0JlNw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_GiRCILhZEfGBDbnOg0JlNw" target="_-25VgK4eEfGSsY55kcG7Og" source="_8OycoLhXEfGBDbnOg0JlNw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_GiRCIbhZEfGBDbnOg0JlNw"/>
        <condition xmi:type="expression:Expression" xmi:id="_GiRCIrhZEfGBDbnOg0JlNw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_buZBoLhZEfGBDbnOg0JlNw" target="__CbgUKftEfGZSb5q5b0p5g" source="_-25VgK4eEfGSsY55kcG7Og">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_buZBobhZEfGBDbnOg0JlNw"/>
        <condition xmi:type="expression:Expression" xmi:id="_buZBorhZEfGBDbnOg0JlNw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_jhaSALhZEfGBDbnOg0JlNw" target="_Dk1VwLhbEfGBDbnOg0JlNw" source="__CbgUKftEfGZSb5q5b0p5g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_jhaSAbhZEfGBDbnOg0JlNw"/>
        <condition xmi:type="expression:Expression" xmi:id="_Dk3yArhbEfGBDbnOg0JlNw" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kfpb4LhZEfGBDbnOg0JlNw" name="no" target="_pVRY8LhXEfGBDbnOg0JlNw" source="_Dk1VwLhbEfGBDbnOg0JlNw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kfpb4bhZEfGBDbnOg0JlNw"/>
        <condition xmi:type="expression:Expression" xmi:id="_Dk3yALhbEfGBDbnOg0JlNw" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_9Ajl4LhZEfGBDbnOg0JlNw" target="_jcCGgKyXEfGxAq-kOcKFjQ" source="_iL-CQKyWEfGxAq-kOcKFjQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_9Ajl4bhZEfGBDbnOg0JlNw"/>
        <condition xmi:type="expression:Expression" xmi:id="_9Ajl4rhZEfGBDbnOg0JlNw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_UpwEwLhaEfGBDbnOg0JlNw" name="si" target="_dEJeMLhaEfGBDbnOg0JlNw" source="_Dk1VwLhbEfGBDbnOg0JlNw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_UpwEwbhaEfGBDbnOg0JlNw"/>
        <condition xmi:type="expression:Expression" xmi:id="_Dk3yAbhbEfGBDbnOg0JlNw" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_rAgEULhaEfGBDbnOg0JlNw" target="_zfop0KyTEfGxAq-kOcKFjQ" source="_dEJeMLhaEfGBDbnOg0JlNw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_rAgEUbhaEfGBDbnOg0JlNw"/>
        <condition xmi:type="expression:Expression" xmi:id="_rAgEUrhaEfGBDbnOg0JlNw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_teKZkLhaEfGBDbnOg0JlNw" target="_Zu9ZsKyWEfGxAq-kOcKFjQ" source="_zfop0KyTEfGxAq-kOcKFjQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_teKZkbhaEfGBDbnOg0JlNw"/>
        <condition xmi:type="expression:Expression" xmi:id="_teLAoLhaEfGBDbnOg0JlNw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_vDk4MLhaEfGBDbnOg0JlNw" target="_iL-CQKyWEfGxAq-kOcKFjQ" source="_Zu9ZsKyWEfGxAq-kOcKFjQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_vDk4MbhaEfGBDbnOg0JlNw"/>
        <condition xmi:type="expression:Expression" xmi:id="_vDk4MrhaEfGBDbnOg0JlNw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_r-AG16flEfGZSb5q5b0p5g" documentation="This is an example of actor that is mapped to any ACME users" name="Employee actor" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_XDEoIKfpEfGZSb5q5b0p5g" name="Municipio"/>
      <actors xmi:type="process:Actor" xmi:id="_CUNXYK7DEfGSsY55kcG7Og" name="CentroCoordinador"/>
      <actors xmi:type="process:Actor" xmi:id="_DVdZAK7DEfGSsY55kcG7Og" name="ONG"/>
      <contract xmi:type="process:Contract" xmi:id="_r-AG2KflEfGZSb5q5b0p5g"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_r-AG2aflEfGZSb5q5b0p5g">
        <name xmi:type="expression:Expression" xmi:id="_r-AG2qflEfGZSb5q5b0p5g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_r-AG26flEfGZSb5q5b0p5g" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_r-AG3KflEfGZSb5q5b0p5g">
        <name xmi:type="expression:Expression" xmi:id="_r-AG3aflEfGZSb5q5b0p5g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_r-AG3qflEfGZSb5q5b0p5g" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_r-AG36flEfGZSb5q5b0p5g">
        <name xmi:type="expression:Expression" xmi:id="_r-AG4KflEfGZSb5q5b0p5g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_r-AG4aflEfGZSb5q5b0p5g" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_r-AG4qflEfGZSb5q5b0p5g">
        <name xmi:type="expression:Expression" xmi:id="_r-AG46flEfGZSb5q5b0p5g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_r-AG5KflEfGZSb5q5b0p5g" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_r-AG5aflEfGZSb5q5b0p5g">
        <name xmi:type="expression:Expression" xmi:id="_r-AG5qflEfGZSb5q5b0p5g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_r-AG56flEfGZSb5q5b0p5g" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_r-AG6KflEfGZSb5q5b0p5g" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_r-AG6aflEfGZSb5q5b0p5g" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_r-AG6qflEfGZSb5q5b0p5g" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_r-AG66flEfGZSb5q5b0p5g" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_r-AG7KflEfGZSb5q5b0p5g" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_r-AG7aflEfGZSb5q5b0p5g" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_r-AG7qflEfGZSb5q5b0p5g" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_r-AG76flEfGZSb5q5b0p5g" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_r-AG8KflEfGZSb5q5b0p5g" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_r-AG8aflEfGZSb5q5b0p5g" type="Process" element="_r9-4oKflEfGZSb5q5b0p5g" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_r-AG8qflEfGZSb5q5b0p5g" type="2007" element="_r9_fsKflEfGZSb5q5b0p5g">
      <children xmi:type="notation:DecorationNode" xmi:id="_r-At0KflEfGZSb5q5b0p5g" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_r-At0aflEfGZSb5q5b0p5g" type="7001">
        <children xmi:type="notation:Node" xmi:id="_r-At0qflEfGZSb5q5b0p5g" type="3007" element="_r9_fsaflEfGZSb5q5b0p5g">
          <children xmi:type="notation:DecorationNode" xmi:id="_r-At06flEfGZSb5q5b0p5g" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_r-At1KflEfGZSb5q5b0p5g" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_r-At1aflEfGZSb5q5b0p5g" type="3005" element="_r-AGw6flEfGZSb5q5b0p5g" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_r-At1qflEfGZSb5q5b0p5g" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_r-At16flEfGZSb5q5b0p5g" x="160" y="60" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_r-At2KflEfGZSb5q5b0p5g" type="3002" element="_r9_fsqflEfGZSb5q5b0p5g" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_r-At2aflEfGZSb5q5b0p5g" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_r-At2qflEfGZSb5q5b0p5g" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_r-At26flEfGZSb5q5b0p5g" x="63" y="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_dEKFSLhaEfGBDbnOg0JlNw" type="3027" element="_dEJeMLhaEfGBDbnOg0JlNw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_dEKFSrhaEfGBDbnOg0JlNw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_dEKFSbhaEfGBDbnOg0JlNw" x="1220" y="68" width="120" height="60"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_r-At3KflEfGZSb5q5b0p5g"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_r-At3aflEfGZSb5q5b0p5g" fontName=".AppleSystemUIFont"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_r-At3qflEfGZSb5q5b0p5g"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_r-At36flEfGZSb5q5b0p5g"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_r-At4KflEfGZSb5q5b0p5g"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_nFsXMKfpEfGZSb5q5b0p5g" type="3007" element="_nFnesKfpEfGZSb5q5b0p5g">
          <children xmi:type="notation:DecorationNode" xmi:id="_nFwooKfpEfGZSb5q5b0p5g" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_nFxPsKfpEfGZSb5q5b0p5g" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_91ODIKfpEfGZSb5q5b0p5g" type="3005" element="_91GHUKfpEfGZSb5q5b0p5g" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_91OqMKfpEfGZSb5q5b0p5g" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_91ODIafpEfGZSb5q5b0p5g" x="897" y="113" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Zu9ZvayWEfGxAq-kOcKFjQ" type="3005" element="_Zu9ZsKyWEfGxAq-kOcKFjQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Zu9Zv6yWEfGxAq-kOcKFjQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Zu9ZvqyWEfGxAq-kOcKFjQ" x="1790" y="56" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_jcDUoKyXEfGxAq-kOcKFjQ" type="3003" element="_jcCGgKyXEfGxAq-kOcKFjQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_jcDUoqyXEfGxAq-kOcKFjQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_jcDUo6yXEfGxAq-kOcKFjQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_jcDUoayXEfGxAq-kOcKFjQ" x="2550" y="88"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_pWHGcLhXEfGBDbnOg0JlNw" type="3006" element="_pVRY8LhXEfGBDbnOg0JlNw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_pWHtgLhXEfGBDbnOg0JlNw" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_pWHGcbhXEfGBDbnOg0JlNw" x="213" y="134" width="120" height="60"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_nFsXMafpEfGZSb5q5b0p5g"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_nFsXMqfpEfGZSb5q5b0p5g" fontName=".AppleSystemUIFont"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_nFsXM6fpEfGZSb5q5b0p5g"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_nFxPsafpEfGZSb5q5b0p5g"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_nFsXNKfpEfGZSb5q5b0p5g" x="48" y="465" width="2647" height="309"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_gVq_cKfqEfGZSb5q5b0p5g" type="3007" element="_gVcV8KfqEfGZSb5q5b0p5g">
          <children xmi:type="notation:DecorationNode" xmi:id="_gVv38KfqEfGZSb5q5b0p5g" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_gVwfAKfqEfGZSb5q5b0p5g" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_iL-pXKyWEfGxAq-kOcKFjQ" type="3005" element="_iL-CQKyWEfGxAq-kOcKFjQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_iL_QYKyWEfGxAq-kOcKFjQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_iL-pXayWEfGxAq-kOcKFjQ" x="1790" y="64" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_-258kK4eEfGSsY55kcG7Og" type="3027" element="_-25VgK4eEfGSsY55kcG7Og" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_-258kq4eEfGSsY55kcG7Og" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_-258ka4eEfGSsY55kcG7Og" x="1182" y="51" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_8OzqwLhXEfGBDbnOg0JlNw" type="3005" element="_8OycoLhXEfGBDbnOg0JlNw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_8OzqwrhXEfGBDbnOg0JlNw" type="5005"/>
              <children xmi:type="notation:Shape" xmi:id="_ZQOLgLhYEfGBDbnOg0JlNw" type="3043" element="_ZQNkcLhYEfGBDbnOg0JlNw" fontName="Segoe UI">
                <children xmi:type="notation:DecorationNode" xmi:id="_ZQOykLhYEfGBDbnOg0JlNw" type="5055">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="_ZQOykbhYEfGBDbnOg0JlNw" x="11" y="12"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ZQOLgbhYEfGBDbnOg0JlNw"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8OzqwbhXEfGBDbnOg0JlNw" x="71" y="64" width="120" height="60"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_gVrmgKfqEfGZSb5q5b0p5g"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_gVsNkKfqEfGZSb5q5b0p5g" fontName=".AppleSystemUIFont"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_gVsNkafqEfGZSb5q5b0p5g"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_gVwfAafqEfGZSb5q5b0p5g"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_gVsNkqfqEfGZSb5q5b0p5g" x="48" y="740" width="2647" height="218"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_7YBrIKftEfGZSb5q5b0p5g" type="3007" element="_7XVHkKftEfGZSb5q5b0p5g">
          <children xmi:type="notation:DecorationNode" xmi:id="_7YF8kKftEfGZSb5q5b0p5g" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_7YGjoKftEfGZSb5q5b0p5g" type="7002">
            <children xmi:type="notation:Shape" xmi:id="__CgY0KftEfGZSb5q5b0p5g" type="3027" element="__CbgUKftEfGZSb5q5b0p5g" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="__Cg_4KftEfGZSb5q5b0p5g" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="__CgY0aftEfGZSb5q5b0p5g" x="805" y="25" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_zfpQ4KyTEfGxAq-kOcKFjQ" type="3027" element="_zfop0KyTEfGxAq-kOcKFjQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_zfpQ4qyTEfGxAq-kOcKFjQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_zfpQ4ayTEfGxAq-kOcKFjQ" x="1513" y="41" width="130" height="65"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Dk1VxLhbEfGBDbnOg0JlNw" type="3009" element="_Dk1VwLhbEfGBDbnOg0JlNw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_Dk180LhbEfGBDbnOg0JlNw" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Dk180bhbEfGBDbnOg0JlNw" x="19" y="6"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Dk1VxbhbEfGBDbnOg0JlNw" x="628" y="100" width="43" height="43"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_7YCSMKftEfGZSb5q5b0p5g"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_7YCSMaftEfGZSb5q5b0p5g" fontName=".AppleSystemUIFont"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_7YCSMqftEfGZSb5q5b0p5g"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_7YGjoaftEfGZSb5q5b0p5g"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_7YCSM6ftEfGZSb5q5b0p5g" x="23" y="10" width="2497" height="215"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_r-At4aflEfGZSb5q5b0p5g"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_r-At4qflEfGZSb5q5b0p5g" fontName=".AppleSystemUIFont"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_r-At46flEfGZSb5q5b0p5g"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_r-At5KflEfGZSb5q5b0p5g"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_r-At5aflEfGZSb5q5b0p5g" width="2670" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_r-At5qflEfGZSb5q5b0p5g"/>
    <edges xmi:type="notation:Connector" xmi:id="_r-At56flEfGZSb5q5b0p5g" type="4001" element="_r-AG1KflEfGZSb5q5b0p5g" source="_r-At2KflEfGZSb5q5b0p5g" target="_r-At1aflEfGZSb5q5b0p5g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_r-At6KflEfGZSb5q5b0p5g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_r-At6aflEfGZSb5q5b0p5g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_r-At6qflEfGZSb5q5b0p5g" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_r-At66flEfGZSb5q5b0p5g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_-b5BkKfpEfGZSb5q5b0p5g" type="4001" element="_-b1XMKfpEfGZSb5q5b0p5g" source="_r-At1aflEfGZSb5q5b0p5g" target="_91ODIKfpEfGZSb5q5b0p5g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_-b5ooKfpEfGZSb5q5b0p5g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_-b5ooafpEfGZSb5q5b0p5g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_-b5BkafpEfGZSb5q5b0p5g" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_-b5BkqfpEfGZSb5q5b0p5g" points="[5, 12, -104, -267]$[103, 270, -6, -9]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_-b_vQKfpEfGZSb5q5b0p5g" id="(0.9583333333333334,0.5333333333333333)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_-cAWUKfpEfGZSb5q5b0p5g" id="(0.41,0.18)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_vjaWMLhXEfGBDbnOg0JlNw" type="4001" element="_vjZIELhXEfGBDbnOg0JlNw" source="_pWHGcLhXEfGBDbnOg0JlNw" target="_91ODIKfpEfGZSb5q5b0p5g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_vjbkULhXEfGBDbnOg0JlNw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_vjbkUbhXEfGBDbnOg0JlNw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_vja9QLhXEfGBDbnOg0JlNw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_vja9QbhXEfGBDbnOg0JlNw" points="[22, 8, -166, 34]$[111, 8, -77, 34]$[111, -47, -77, -21]$[184, -47, -4, -21]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_vjenoLhXEfGBDbnOg0JlNw" id="(0.8166666666666667,0.35)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_vjenobhXEfGBDbnOg0JlNw" id="(0.03333333333333333,0.5666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_KD-q0LhYEfGBDbnOg0JlNw" type="4001" element="_KD-DwLhYEfGBDbnOg0JlNw" source="_91ODIKfpEfGZSb5q5b0p5g" target="_8OzqwLhXEfGBDbnOg0JlNw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_KD_R4LhYEfGBDbnOg0JlNw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_KD_R4bhYEfGBDbnOg0JlNw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_KD-q0bhYEfGBDbnOg0JlNw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_KD-q0rhYEfGBDbnOg0JlNw" points="[41, 6, 231, -207]$[41, 27, 231, -186]$[-35, 27, 155, -186]$[-35, 194, 155, -19]$[-212, 194, -22, -19]$[-212, 207, -22, -6]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_KEBHELhYEfGBDbnOg0JlNw" id="(0.0,0.9)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_KEBHEbhYEfGBDbnOg0JlNw" id="(0.6833333333333333,0.1)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_GiRpMLhZEfGBDbnOg0JlNw" type="4001" element="_GiRCILhZEfGBDbnOg0JlNw" source="_8OzqwLhXEfGBDbnOg0JlNw" target="_-258kK4eEfGSsY55kcG7Og" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_GiSQQLhZEfGBDbnOg0JlNw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_GiSQQbhZEfGBDbnOg0JlNw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_GiRpMbhZEfGBDbnOg0JlNw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_GiRpMrhZEfGBDbnOg0JlNw" points="[5, 0, -186, -12]$[191, 30, 0, 18]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_GiTeYLhZEfGBDbnOg0JlNw" id="(0.95,0.6)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_GiTeYbhZEfGBDbnOg0JlNw" id="(0.14166666666666666,0.6166666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_buZosLhZEfGBDbnOg0JlNw" type="4001" element="_buZBoLhZEfGBDbnOg0JlNw" source="_-258kK4eEfGSsY55kcG7Og" target="__CgY0KftEfGZSb5q5b0p5g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_buZos7hZEfGBDbnOg0JlNw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_buZotLhZEfGBDbnOg0JlNw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_buZosbhZEfGBDbnOg0JlNw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_buZosrhZEfGBDbnOg0JlNw" points="[14, 1, -323, 829]$[426, 1, 89, 829]$[426, -476, 89, 352]$[369, -476, 32, 352]$[369, -798, 32, 30]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_bubd4LhZEfGBDbnOg0JlNw" id="(0.8833333333333333,0.48333333333333334)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_jha5ELhZEfGBDbnOg0JlNw" type="4001" element="_jhaSALhZEfGBDbnOg0JlNw" source="__CgY0KftEfGZSb5q5b0p5g" target="_Dk1VxLhbEfGBDbnOg0JlNw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_jha5E7hZEfGBDbnOg0JlNw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_jha5FLhZEfGBDbnOg0JlNw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_jha5EbhZEfGBDbnOg0JlNw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_jha5ErhZEfGBDbnOg0JlNw" points="[-21, 6, 158, -52]$[-180, 54, -1, -4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_jhcHMLhZEfGBDbnOg0JlNw" id="(0.175,0.43333333333333335)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_jhcuQLhZEfGBDbnOg0JlNw" id="(0.4418604651162791,0.13953488372093023)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kfpb47hZEfGBDbnOg0JlNw" type="4001" element="_kfpb4LhZEfGBDbnOg0JlNw" source="_Dk1VxLhbEfGBDbnOg0JlNw" target="_pWHGcLhXEfGBDbnOg0JlNw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_kfqC8LhZEfGBDbnOg0JlNw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kfqC8bhZEfGBDbnOg0JlNw" x="-80" y="235"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kfpb5LhZEfGBDbnOg0JlNw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kfpb5bhZEfGBDbnOg0JlNw" points="[-6, -8, 355, -505]$[-22, -8, 339, -505]$[-22, 271, 339, -226]$[-306, 271, 55, -226]$[-306, 467, 55, -30]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_kfrRELhZEfGBDbnOg0JlNw" id="(0.13953488372093023,0.6744186046511628)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_9AkM8LhZEfGBDbnOg0JlNw" type="4001" element="_9Ajl4LhZEfGBDbnOg0JlNw" source="_iL-pXKyWEfGxAq-kOcKFjQ" target="_jcDUoKyXEfGxAq-kOcKFjQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_9AkM87hZEfGBDbnOg0JlNw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_9AkM9LhZEfGBDbnOg0JlNw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_9AkM8bhZEfGBDbnOg0JlNw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_9AkM8rhZEfGBDbnOg0JlNw" points="[18, -10, -495, 272]$[513, -281, 0, 1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_9AmCILhZEfGBDbnOg0JlNw" id="(0.85,0.5)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_9AmCIbhZEfGBDbnOg0JlNw" id="(0.5,0.9333333333333333)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_UpwEw7haEfGBDbnOg0JlNw" type="4001" element="_UpwEwLhaEfGBDbnOg0JlNw" source="_Dk1VxLhbEfGBDbnOg0JlNw" target="_dEKFSLhaEfGBDbnOg0JlNw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_UpwExrhaEfGBDbnOg0JlNw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_UpwEx7haEfGBDbnOg0JlNw" x="-284" y="-9"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_UpwExLhaEfGBDbnOg0JlNw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_UpwExbhaEfGBDbnOg0JlNw" points="[6, 0, -609, -192]$[464, 0, -151, -192]$[464, 175, -151, -17]$[555, 175, -60, -17]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_UpxS4LhaEfGBDbnOg0JlNw" id="(0.8604651162790697,0.4883720930232558)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_rAgEU7haEfGBDbnOg0JlNw" type="4001" element="_rAgEULhaEfGBDbnOg0JlNw" source="_dEKFSLhaEfGBDbnOg0JlNw" target="_zfpQ4KyTEfGxAq-kOcKFjQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_rAgEVrhaEfGBDbnOg0JlNw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_rAgEV7haEfGBDbnOg0JlNw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_rAgEVLhaEfGBDbnOg0JlNw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_rAgEVbhaEfGBDbnOg0JlNw" points="[26, 11, -195, 229]$[39, 11, -182, 229]$[39, -161, -182, 57]$[199, -161, -22, 57]$[199, -196, -22, 22]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_rAh5gLhaEfGBDbnOg0JlNw" id="(0.7833333333333333,0.31666666666666665)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_rAh5gbhaEfGBDbnOg0JlNw" id="(0.16923076923076924,0.6615384615384615)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_teLAobhaEfGBDbnOg0JlNw" type="4001" element="_teKZkLhaEfGBDbnOg0JlNw" source="_zfpQ4KyTEfGxAq-kOcKFjQ" target="_Zu9ZvayWEfGxAq-kOcKFjQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_teLApLhaEfGBDbnOg0JlNw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_teLApbhaEfGBDbnOg0JlNw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_teLAorhaEfGBDbnOg0JlNw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_teLAo7haEfGBDbnOg0JlNw" points="[65, 0, -207, -478]$[79, 0, -193, -478]$[79, 239, -193, -239]$[256, 239, -16, -239]$[256, 448, -16, -30]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_vDlfQLhaEfGBDbnOg0JlNw" type="4001" element="_vDk4MLhaEfGBDbnOg0JlNw" source="_Zu9ZvayWEfGxAq-kOcKFjQ" target="_iL-pXKyWEfGxAq-kOcKFjQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_vDlfQ7haEfGBDbnOg0JlNw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_vDlfRLhaEfGBDbnOg0JlNw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_vDlfQbhaEfGBDbnOg0JlNw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_vDlfQrhaEfGBDbnOg0JlNw" points="[0, 30, 0, -287]$[0, 347, 0, 30]"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
